version: "2"
services:
  database:
    container_name: database_message_api
    image: mongo:4.0
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$BD_USER
      - MONGO_INITDB_ROOT_PASSWORD=$BD_PWD
    volumes:
      - ./volumes/mongo/data/:/data/db
    ports:
      - 27017:27017
    networks:
      localnet:
        ipv4_address: $BD_IP
  api:
    container_name: message_api
    image: message-api:latest
    restart: always
    environment:
      BD_IP: $BD_IP
    depends_on:
      - database
    volumes:
      - ./scripts/insertAdminUserDB.sh:/usr/local/bin/insertAdminUserDB.sh
    # command:
    #   - insertAdminUserDB.sh
    ports:
      - 9090:9090
    networks:
      localnet:
        ipv4_address: 172.30.1.3
networks:
  localnet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16